Repository chingu-voyages/v50-tier3-team-21, pull requests merged in 2024-07, with the labels that each got.

#51 Feature/backend base
  backend/app.js
  backend/config/config.js
  backend/models/User.js
  backend/models/index.js
  backend/models/user.test.js
  backend/package-lock.json
  backend/package.json
Labels: task

#54 Data Migration from the API to the PostgreSQL
  backend/models/Category.js
  backend/models/FoodItem.js
  backend/models/FoodItemCategory.js
  backend/models/Restaurant.js
  backend/seeders/API2db.js
  backend/seeders/checkAPI2db.js
Labels: must_have

#88 bug-fix: refresh token and user save #86
  backend/controllers/authController.js
  backend/controllers/foodItemsController.js
  backend/env-sample
Labels: bug

#91 Refactor verifyToken controller
  README.md
  backend/controllers/authController.js
  backend/routes/authRoutes.js
Labels: enhancement

#93 adds profile update and minor code structure refactor
  backend/app.js
  backend/controllers/authController.js
  backend/controllers/profileController.js
  backend/middlewares/authorization.js
  backend/middlewares/validations.js
  backend/package-lock.json
  backend/routes/authRoutes.js
  backend/routes/foodItemsRoutes.js
  backend/routes/nearbyRestaurantRoutes.js
  backend/routes/profileRoutes.js
  backend/yarn.lock
Labels: task

#103 refresh-token revert and User model fix
  README.md
  backend/controllers/authController.js
  backend/helpers/jwt.js
  backend/models/User.js
  backend/models/user.test.js
  backend/routes/authRoutes.js
Labels: bug, enhancement

#107 Feature/resetpassword back
  backend/app.js
  backend/controllers/authController.js
  backend/controllers/resetPasswordController.js
  backend/helpers/jwt.js
  backend/package-lock.json
  backend/package.json
  backend/routes/resetPasswordRoutes.js
  backend/yarn.lock
Labels: bug, enhancement

#105 tests to nearby restaurant search
  backend/controllers/authController.js
  backend/controllers/nearbyRestaurantController.js
  backend/controllers/nearbyRestaurantController.test.js
  backend/models/User.test.js
  backend/package.json
Labels: bug, enhancement

#109 fix refactor signup token
  backend/controllers/authController.js
  backend/package-lock.json
  backend/package.json
  backend/yarn.lock
Labels: bug, enhancement

#111 Feature/resetpassword back
  backend/app.js
  backend/controllers/resetPasswordController.js
  backend/env-sample
  backend/mail.test.js
  backend/middlewares/mail.js
  backend/package-lock.json
  backend/package.json
  backend/routes/resetPasswordRoutes.js
  backend/swagger.json
  backend/yarn.lock
Labels: must_have

#113 Reset Password redirection to frontend
  backend/controllers/authController.js
  backend/controllers/resetPasswordController.js
  backend/env-sample
Labels: task

#117 fix refresh token on login uses own key
  backend/controllers/authController.js
Labels: bug

#118 update swaggerui for reset password
  backend/package.json
  backend/swagger.json
Labels: enhancement

#121 Wif/deployment
  backend/app.js
  frontend/vite.config.ts
Labels: enhancement, nice_to_have

#125 Feature/create order
  backend/app.js
  backend/controllers/orderController.js
  backend/models/Category.js
  backend/models/Order.js
  backend/models/OrderFoodItem.js
  backend/routes/orderRoutes.js
Labels: task, must_have

#130 Update Order and Docs
  backend/app.js
  backend/controllers/orderController.js
  backend/models/Order.js
  backend/routes/orderRoutes.js
  backend/swagger.json
Labels: enhancement, task, must_have
